### PR TITLE
Fix reading of Iceberg Parquet write properties for row group, page a…

### LINKED ISSUE #182: Parquet writer doesn't consider configuration properties in some cases (rowGroupSize, pageSize, dictionarySize)
I was writing a test case for https://github.com/apache/incubator-iceberg/issues/132 and noticed the code path [here](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java#L191) looks like it's expecting the values to be read via `Configuration` as bootstrapped from Iceberg to Parquet names [here](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java#L162) but digging into this it ends up instantiating a `ParquetWriter` that is expecting that `rowGroupSize` and `ParquetProperties` were configured explicitly instead of reading via key/values in the configuration. This made it so I couldn't generate a file via the iceberg `Parquet` API with multiple row groups by artificially reducing the row group size for the test.

Also, I'm not sure the other branch [here](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java#L188) ends up respecting the other properties such as dictionary and page size (I couldn't find where they were configured at least) - `rowGroupSize` is set explicitly though in that case. In that code path Iceberg's own `ParquetWriter` is used which delegates to a Parquet's `ParquetFileWriter` but I don't see where page/dictionary size is configured in that case. In comparison the other code path has `InternalParquetRecordWriter` --> `ParquetFileWriter` where `InternalParquetRecordWriter` has a `ParquetProperties` which is used to instantiate the `ColumnWriteStore` which considers page size. The dictionary size used appears to just get the default value from the properties constructed [here](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java#L66). Also those properties are making the Parquet format version always hardcoded as V1, not sure if that is intended?

### PR DESCRIPTION
**Pull request by ryanrupp**
…nd dictionary size

Previously this was setting the key/value for these properties in the Hadoop Configuration but the Parquet write APIs used here require explicitly setting them via ParquetProperties.

Fixes #182

### CODE REVIEW

File: parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java [hunk 1]
```diff
@@ -183,10 +177,13 @@ void forwardConfig(String parquetProperty, String icebergProperty, String defaul
           conf.set(entry.getKey(), entry.getValue());
         }
 
-        long rowGroupSize = Long.parseLong(config.getOrDefault(
-            PARQUET_ROW_GROUP_SIZE_BYTES, PARQUET_ROW_GROUP_SIZE_BYTES_DEFAULT));
+        ParquetProperties parquetProperties = ParquetProperties.builder()
```
Comment (rdblue) [inline parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java]: Looks like this dropped `withWriterVersion` that was set in `ParquetWriter`.

File: parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java [hunk 2]
```diff
@@ -144,27 +145,20 @@ private CompressionCodecName codec() {
...
-      // add Parquet configuration
-      forwardConfig("parquet.block.size",
-          PARQUET_ROW_GROUP_SIZE_BYTES, PARQUET_ROW_GROUP_SIZE_BYTES_DEFAULT);
-      forwardConfig("parquet.page.size",
-          PARQUET_PAGE_SIZE_BYTES, PARQUET_PAGE_SIZE_BYTES_DEFAULT);
-      forwardConfig("parquet.dictionary.page.size",
-          PARQUET_DICT_SIZE_BYTES, PARQUET_DICT_SIZE_BYTES_DEFAULT);
+      // Map Iceberg properties to pass down to the Parquet writer
+      int rowGroupSize = Integer.parseInt(config.getOrDefault(
+              PARQUET_ROW_GROUP_SIZE_BYTES, PARQUET_ROW_GROUP_SIZE_BYTES_DEFAULT));
```
Comment (rdblue) [inline parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java]: Indentation should use 2 spaces. Continuing indentation should be 4 spaces.

File: parquet/src/test/java/org/apache/iceberg/parquet/TestParquetMetrics.java [hunk 3]
```diff
@@ -292,14 +290,6 @@ private void assertCounts(int fieldId, long valueCount, long nullValueCount, Met
...
-    File tmpFolder = temp.newFolder("parquet");
-    String filename = UUID.randomUUID().toString();
-    File file = new File(tmpFolder, FileFormat.PARQUET.addExtension(filename));
-    try (FileAppender<Record> writer = Parquet.write(localOutput(file))
-        .schema(schema)
-        .build()) {
-      writer.addAll(Lists.newArrayList(records));
-    }
-    return file;
+    return TestParquet.writeRecords(temp, schema, Collections.emptyMap(), null, records);
```
Comment (rdblue) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestParquetMetrics.java]: Tests shouldn't use methods in other tests because they are hard to keep track of. If you want to use the same method, then let's move it to a test utility class, or a base class.

**Comment by rdblue** [comment]
Thanks for working on this, @ryanrupp! It looks close, but there are a few things to fix.

File: parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java (hunk 1 above)
Comment (ryanrupp) [reply parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java]: I let this default as the `else` path defaults as well (so both use V1 by default). Thinking I'll make this more explicit and just have a constant in this class hardcoded to V1 then for now and both paths will use that.

Comment (ryanrupp) [reply parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java]: Not sure if this should be configurable though? Will hardcode it to V1 for now.

File: parquet/src/test/java/org/apache/iceberg/parquet/TestParquetMetrics.java (hunk 3 above)
Comment (ryanrupp) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestParquetMetrics.java]: Did a base class here just for convenience so the `@Rule` for the temp folder doesn't need to be passed around.

File: parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java (hunk 1 above)
Comment (ryanrupp) [reply parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java]: Looks sort of weird just hardcoding it but left it like this for future logic that wants to detect it in some way e.g. explicitly set or via iceberg properties

**Comment by ryanrupp** [comment]
Not sure if you squash merge in this project but I can rebase/squash the commits down after review. Kept them separate to see the post review change set.

File: parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+  @Test
+  public void testRowGroupSizeConfigurableWithWriter() throws IOException {
+    File parquetFile = generateFileWithTwoRowGroups(ParquetAvroWriter::buildWriter);
+
+    try (ParquetFileReader reader = ParquetFileReader.open(ParquetIO.file(localInput(parquetFile)))) {
+      Assert.assertEquals(2, reader.getRowGroups().size());
+    }
+  }
+
+  private File generateFileWithTwoRowGroups(Function<MessageType, ParquetValueWriter<?>> createWriterFunc)
```
Comment (aokolnychyi) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java]: Does it make sense to generalize this method and expose it in the base test class? We will need this functionality to test metrics collection with multiple row groups #132.

Comment (ryanrupp) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java]: Yeah I actually ran into this issue when writing a test for #132. I'll probably pull it down to the base class added here as part of the change of the change for #132. Not sure how generic it needs to be, the original test I wrote was the same logic basically and just validated the max int was 101 after the metrics rolled up row groups. Relies a bit on understanding the actual data being added e.g. originally I just set the rowGroup size to 1 byte and then internally there's another threshold to only check this every 100 records, there is some warning logging that happens though if after 100 records the bytes consumed are 3x the desired row group size (this is why I did int size * 100) - it's just log noise though really.

**Comment by rdblue** [comment]
We squash and merge to commit changes to master, so no need to squash here. My general rule is to do whatever you think makes the PR easiest to review.

**Comment by rdblue** [comment]
+1 from me! Thanks for fixing this, @ryanrupp!
