### PR TITLE
Fix missing close call for Avro with container reuse.

### LINKED ISSUE #104: ManifestReader is not properly closed in BaseTableScan
It seems `ManifestReader` is not closed properly in some cases. `ManifestReader` is `CloseableGroup` and we add `AvroIterable` to the list of closeables. However, `ManifestReader$close` is not called.

One way to reproduce this is to run `TestParquetWrite`.

```
[Finalizer] WARN com.netflix.iceberg.hadoop.HadoopStreams - Unclosed input stream created by:
	com.netflix.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.<init>(HadoopStreams.java:78)
	com.netflix.iceberg.hadoop.HadoopStreams.wrap(HadoopStreams.java:53)
	com.netflix.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:125)
	com.netflix.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:95)
	com.netflix.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)
	com.google.common.collect.Iterables$6.iterator(Iterables.java:585)
	com.google.common.collect.Iterables$8.iterator(Iterables.java:709)
	com.netflix.iceberg.ManifestReader.iterator(ManifestReader.java:225)
	com.netflix.iceberg.FilteredManifest.iterator(FilteredManifest.java:124)
	com.google.common.collect.Iterables$8.iterator(Iterables.java:709)
	com.google.common.collect.Iterables$3.transform(Iterables.java:508)
	com.google.common.collect.Iterables$3.transform(Iterables.java:505)
	com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	com.netflix.iceberg.util.BinPacking$PackingIterator.hasNext(BinPacking.java:91)
	com.netflix.iceberg.io.CloseableIterable$4$1.hasNext(CloseableIterable.java:92)
	com.google.common.collect.Iterators.addAll(Iterators.java:356)
	com.google.common.collect.Lists.newArrayList(Lists.java:147)
	com.google.common.collect.Lists.newArrayList(Lists.java:129)
	com.netflix.iceberg.spark.source.Reader.tasks(Reader.java:209)
	com.netflix.iceberg.spark.source.Reader.planInputPartitions(Reader.java:135)
	org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.partitions$lzycompute(DataSourceV2ScanExec.scala:76)
...
```

My suspicion is that we have a problem in `BaseTableScan$planFiles`. Specifically, this piece:
```
      ConcurrentLinkedQueue<Closeable> toClose = new ConcurrentLinkedQueue<>();
      Iterable<Iterable<FileScanTask>> readers = Iterables.transform(
          matchingManifests,
          manifest -> {
            ManifestReader reader = ManifestReader.read(ops.io().newInputFile(manifest.path()));
            toClose.add(reader);
            String schemaString = SchemaParser.toJson(reader.spec().schema());
            String specString = PartitionSpecParser.toJson(reader.spec());
            ResidualEvaluator residuals = new ResidualEvaluator(reader.spec(), rowFilter);
            return Iterables.transform(
                reader.filterRows(rowFilter).select(SNAPSHOT_COLUMNS),
                file -> new BaseFileScanTask(file, schemaString, specString, residuals)
            );
          });

      if (PLAN_SCANS_WITH_WORKER_POOL && snapshot.manifests().size() > 1) {
        return CloseableIterable.combine(
            new ParallelIterable<>(readers, getWorkerPool()),
            toClose);
      } else {
        return CloseableIterable.combine(Iterables.concat(readers), toClose);
      }
```

The closure that adds `ManifestReader reader` to `toClose` is lazy. Hence, `toClose` is empty when we return `CloseableIterable.combine(Iterables.concat(readers), toClose)`.

### PR DESCRIPTION
**Pull request by rdblue**
This fixes #104.

### CODE REVIEW

**Comment by rdblue** [comment]
@aokolnychyi & @rdsr, this is the fix for manifest files that are being left open after planning scans. Can you take a look?

File: core/src/main/java/com/netflix/iceberg/avro/AvroIterable.java [hunk 1]
```diff
@@ -80,12 +80,12 @@
       reader = new AvroRangeIterator<>(reader, start, end);
     }
 
+    addCloseable(reader);
```
Comment (rdsr) [inline core/src/main/java/com/netflix/iceberg/avro/AvroIterable.java]: nice catch

**Comment by rdblue** [comment]
Merged. Thanks for reviewing, @rdsr!
