### PR TITLE
Fix collection of bounds for small decimals in ParquetMetrics

### LINKED ISSUE #125: ParquetMetrics computes wrong lower/upper bounds for small decimals
It seems `ParquetMetrics` computes wrong lower/upper bounds for decimals that are represented as int64 in Parquet. Consequently, Iceberg can filter out data files that contain relevant data for a query.

Create a Parquet file with one row:
```
    Schema schema = new Schema(
      optional(1, "decimalCol", Types.DecimalType.of(10, 2))
    );

    GenericData.Record record = new GenericData.Record(AvroSchemaUtil.convert(schema.asStruct()));
    record.put(0, new BigDecimal("3.50"));

    File parquetFile = newParquetFile();
    try (FileAppender<GenericData.Record> writer = Parquet.write(localOutput(parquetFile))
        .schema(schema)
        .build()) {
      writer.add(record);
    }
```

Explore this file using parquet-tools (min/max values are correct):
```
file schema: table 
--------------------------------------------------------------------------------
decimalCol:  OPTIONAL INT64 O:DECIMAL R:0 D:1

row group 1: RC:1 TS:75 OFFSET:4 
--------------------------------------------------------------------------------
decimalCol:   INT64 GZIP DO:0 FPO:4 SZ:91/75/0.82 VC:1 ENC:BIT_PACKED,PLAIN,RLE ST:[min: 3.50, max: 3.50, num_nulls: 0]
```
Create an Iceberg table:
```
    String tableLocation = newTableLocation();
    Configuration conf = new Configuration();
    HadoopTables hadoopTables = new HadoopTables(conf);
    Table table = hadoopTables.create(schema, tableLocation);
```

Append the Parquet file to the table:
```
    DataFile dataFile = DataFiles.builder(PartitionSpec.unpartitioned())
      .withFileSizeInBytes(parquetFile.length())
      .withPath(parquetFile.toString())
      .withMetrics(fromInputFile(localInput(parquetFile)))
      .build();

    table.newAppend().appendFile(dataFile).commit();
```

Query the table via Spark:
```
    Dataset<Row> df = spark.read()
      .format("iceberg")
      .load(tableLocation);

    df.show();
    +----------+
    |decimalCol|
    +----------+
    |      3.50|
    +----------+
    df.where("decimalCol = 3.50").show();
    +----------+
    |decimalCol|
    +----------+
    +----------+
    df.where("decimalCol = CAST(3.50 AS DECIMAL(10,2))").show();
    +----------+
    |decimalCol|
    +----------+
    +----------+
```

This happens because `ParquetMetrics` uses `ParquetConversions$fromParquetPrimitive`, which assumes that decimals are always represented as binary.

In this particular case, `org.apache.parquet.column.statistics.Statistics$genericGetMin` will return a long value.

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR resolves #125.

`ParquetMetrics` uses `ParquetConversions$fromParquetPrimitive`, which assumes that decimals are always represented as binary in Parquet. The last statement is not true according to[ the Parquet spec](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md).

As a consequence, Iceberg might collect invalid lower/upper bounds that can lead to skipping wrong files. See the issue description for an example.

### CODE REVIEW

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+import java.math.BigDecimal;
+import java.nio.ByteBuffer;
+import java.nio.CharBuffer;
+import java.util.Map;
+import java.util.UUID;
+
+import static com.netflix.iceberg.Files.localInput;
+import static com.netflix.iceberg.Files.localOutput;
+import static com.netflix.iceberg.types.Conversions.fromByteBuffer;
+import static com.netflix.iceberg.types.Types.*;
```
Comment (aokolnychyi) [inline parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I usually prefer to avoid wildcard imports but we really use every data type within the tests. Therefore, it seems reasonable here.

File: parquet/src/main/java/com/netflix/iceberg/parquet/ParquetMetrics.java [hunk 2]
```diff
@@ -86,9 +86,9 @@ public static Metrics fromMetadata(ParquetMetadata metadata) {
           Types.NestedField field = fileSchema.asStruct().field(fieldId);
           if (field != null && stats.hasNonNullValue()) {
             updateMin(lowerBounds, fieldId,
-                fromParquetPrimitive(field.type(), stats.genericGetMin()));
+              fromParquetPrimitive(field.type(), column.getPrimitiveType(), stats.genericGetMin()));
```
Comment (rdblue) [inline parquet/src/main/java/com/netflix/iceberg/parquet/ParquetMetrics.java]: Nit: continuation lines should be indented 4 spaces from the start of the statement.

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java (hunk 1 above)
Comment (rdblue) [reply parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I'm okay with this in tests, but I don't generally mind large import blocks because they are maintained by the IDE and are good for context. I'd prefer expanding this but it's up to you.

**Comment by rdblue** [comment]
@aokolnychyi, can you comment on how this fixes the problem? Why doesn't the previous call, for example `Literals.of((Long) value).to(DecimalType.of(9, 2)`, work?

File: parquet/src/main/java/com/netflix/iceberg/parquet/ParquetMetrics.java (hunk 2 above)
Comment (aokolnychyi) [reply parquet/src/main/java/com/netflix/iceberg/parquet/ParquetMetrics.java]: Would no longer fit into 100 characters per line. Do we have such a requirement? I've seen a couple of places where this is not respected.

**Comment by aokolnychyi** [comment]
@rdblue Let's assume we have `3.50` as Decimal(10, 2), which is represented as INT64 in Parquet.

```
file schema: table 
--------------------------------------------------------------------------------
decimalCol:  OPTIONAL INT64 O:DECIMAL R:0 D:1

row group 1: RC:1 TS:75 OFFSET:4 
--------------------------------------------------------------------------------
decimalCol:   INT64 GZIP DO:0 FPO:4 SZ:91/75/0.82 VC:1 ENC:BIT_PACKED,PLAIN,RLE ST:[min: 3.50, max: 3.50, num_nulls: 0]
```

Once we read the footer and call `stats.genericGetMin()` for this decimal column, we will get `350`. This value must be properly scaled (handled by `converterFromParquet`) before creating a literal.

Right now, `Literals.of((Long) 350).to(DecimalType.of(10, 2)` will give us `350.00` instead of `3.50`.

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java (hunk 1 above)
Comment (aokolnychyi) [reply parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I don't have a strong opinion here. I'll expand

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java [hunk 3]
```diff
@@ -0,0 +1,214 @@
...
+    secondRecord.put("intCol", null);
+
+    File parquetFile = writeRecords(schema, firstRecord, secondRecord);
+
+    Metrics metrics = ParquetMetrics.fromInputFile(localInput(parquetFile));
+    Assert.assertEquals(2L, (long) metrics.recordCount());
+    checkFieldMetrics(1, schema, metrics, 2, 2, null, null);
+  }
+
+  private <T> void checkFieldMetrics(int fieldId, Schema schema, Metrics metrics,
```
Comment (rdblue) [inline parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I think these tests would be more readable if this were broken into two: `assertCounts` and `assertBounds`. That way it is clear when calling them that the metrics match the value and null counts, without looking at the implementation. Similarly, it would be clear that the bounds are equal to the given values.

That also allows you to avoid passing in so many arguments. The schema becomes unnecessary because you pass in the field or field type and field ID. As it is now, this gets the field by ID and then accesses its field ID, which is awkward.

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+import java.util.UUID;
+
+import static com.netflix.iceberg.Files.localInput;
+import static com.netflix.iceberg.Files.localOutput;
+import static com.netflix.iceberg.types.Conversions.fromByteBuffer;
+import static com.netflix.iceberg.types.Types.*;
+import static com.netflix.iceberg.types.Types.NestedField.optional;
+import static com.netflix.iceberg.types.Types.NestedField.required;
+
+public class TestParquetMetrics {
```
Comment (rdblue) [inline parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: A test case that is missing is what happens when there are multiple row groups in the file that are merged. We don't have to fix that in this PR, but it would be nice to have at test for it eventually.

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java [hunk 5]
```diff
@@ -0,0 +1,214 @@
...
+      required(13, "binaryCol", BinaryType.get())
+    );
+
+    Record firstRecord = new Record(AvroSchemaUtil.convert(schema.asStruct()));
+    firstRecord.put("booleanCol", true);
+    firstRecord.put("intCol", 3);
+    firstRecord.put("longCol", 5L);
+    firstRecord.put("floatCol", 2.0F);
+    firstRecord.put("doubleCol", 2.0D);
+    firstRecord.put("decimalCol", new BigDecimal("3.50"));
```
Comment (rdblue) [inline parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I think this should test all Parquet decimal storage types: int, long, fixed, and binary. Can you add tests for values other than long?

Comment (aokolnychyi) [reply parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I've added a separate test for decimals as int/long/fixed. Any ideas on how to generate files where decimals represented as binary? `TestMetricsRowGroupFilterTypes` also verifies only int/long/fixed.

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java (hunk 4 above)
Comment (aokolnychyi) [reply parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: I've created #132 so that we don't forget

File: parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java (hunk 5 above)
Comment (rdblue) [reply parquet/src/test/java/com/netflix/iceberg/parquet/TestParquetMetrics.java]: The storage is determined by the decimal precision. Here's how we do it in other tests: https://github.com/apache/incubator-iceberg/blob/master/spark/src/test/java/com/netflix/iceberg/spark/data/AvroDataTest.java#L55-L57

File: parquet/src/main/java/com/netflix/iceberg/parquet/ParquetMetrics.java (hunk 2 above)
Comment (rdblue) [reply parquet/src/main/java/com/netflix/iceberg/parquet/ParquetMetrics.java]: That's probably a mistake then. Thanks for fixing this.

**Comment by rdblue** [comment]
Looks good to me. Thanks @aokolnychyi!
