### PR TITLE
Spark: Add option to allow writing optional to required fields (#510)

### LINKED ISSUE #510: Cannot update an Iceberg dataset from a Parquet file due to "field should be required, but is optional"
Given an Iceberg dataset found at `targetPath` with the following schema named `icebergSchema`:
```
table {
  1: optionalField: optional string
  2: requiredField: required string
}
```
And given an Parquet file found at `sourcePath` with the following schema:
```
message spark_schema {
  optional binary optionalField (UTF8);
  required binary requiredField (UTF8);
}
```
Please note that both have the same schema.

When I do:
```java
sparkSession
        .read().schema(SparkSchemaUtil.convert(icebergSchema)).parquet(sourcePath)
        .write().format("iceberg").mode(SaveMode.Append).save(targetPath);
```
It fails with:
```
Cannot write incompatible dataset to table with schema
table {
  1: optionalField: optional string
  2: requiredField: required string
}
Problems:
* requiredField should be required, but is optional
```

I did debug it and found that at https://github.com/apache/incubator-iceberg/blob/master/api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java#L135 Iceberg checks for `nullable` compatibility for each field which is a correct logic to apply.

Now, at read time Spark loosens the nullability constraint by setting the `nullable` property of each field to `true`. This is done here: https://github.com/apache/spark/blob/branch-2.4/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala#L380.

From what I've found, there are two PRs trying to solve this:

- https://github.com/apache/spark/pull/14124
- https://github.com/apache/spark/pull/17293

In the first one I found this interesting mailing archive [Re: Spark SQL: Preserving Dataframe Schema](https://www.mail-archive.com/user@spark.apache.org/msg39235.html) saying:

> As an academic aside, note that all datatypes are nullable according to the
> SQL Standard.

In the second one I found the [following comment](https://github.com/apache/spark/pull/17293#issuecomment-482328688) as a conclusion:

> Does the closure of this PR imply that setting nullable=false in a custom (user-defined) schema will never have an effect when loading CSV or JSON data from a file? In other words, if someone sets nullable: false in a custom JSON schema, as in the following scenario, it will be ignored?
> ```
> val customSchemaJson = <...some custom JSON schema...>
> val customSchema = DataType.fromJson(customSchemaJson).asInstanceOf[StructType]
> spark.read.schema(customSchema).json("/path/to/data.json")
> ```

With the response:

>Yes, for now. That's what happens now.

With all these, is quite impossible to directly read a parquet file and write its rows to an already present Iceberg dataset having a required field, even though the schemas are the same.

The main use case is directly **updating an Iceberg dataset from a Parquet file**.

Here is a test I put together to demonstrate the issue: https://gist.github.com/andrei-ionescu/e2d4918264b4acea1599ba2516d2f125.

The **proposal** would be — understanding that Spark won't change it soon — for **Iceberg to loosen up by checking the nullability property of nested fields only**.

### PR DESCRIPTION
**Pull request by andrei-ionescu**
This is a proposed fix for #510 — **Cannot update an Iceberg dataset from a Parquet file due to "field should be required, but is optional"**.

The proposes solution is having a write property that will enable or disable the constraint on the nullability field option.

This new option is `check-nullability` and can be set in two ways.

**Data frame option:**

`dataframe.write.option("check-nullability").mode(SaveMode.Append).save(path)`

**Spark Session setup:**

```
SparkSession.builder()
        .master("local[2]")
        .appName("NullableTest")
        .config("spark.sql.iceberg.check-nullability", false)
        .getOrCreate();

dataframe.write.mode(SaveMode.Append).save(path)
```

Fixes #510

### CODE REVIEW

**Comment by andrei-ionescu** [comment]
cc @rdblue @aokolnychyi @fbocse @prodeezy @rominparekh

**Comment by rdblue** [comment]
Thanks for working on this, @andrei-ionescu!

Unfortunately, I think the approach here is incorrect. The problem is that the fields are mapped incorrectly to the Iceberg schema. Iceberg uses position by default, not names. We haven't yet added name mapping support to Parquet (it is in progress for Avro), so if you'd like to work on that it would be great!

**Comment by andrei-ionescu** [comment]
@rdblue: By any chance, did you have a time looking into this and related #510?

**Comment by rdblue** [comment]
This looks like a great start, but I think this should be controlled by an option (possibly a table option and a write option) that ignores nullability in this check. If you want to be able to deploy it globally, then we may want to consider adding a Spark SQL option as well, so you can set it in your cluster environment.

**Comment by andrei-ionescu** [comment]
Thank you @rdblue. I’ll do that.

File: spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+    // this ends with:
+    //
+    //     Cannot write incompatible dataset to table with schema
+    //     table {
+    //       1: optionalField: optional string
+    //       2: requiredField: required string
+    //     }
+    //     Problems:
+    //     * requiredField should be required, but is optional
+    //
```
Comment (manishmalhotrawork) [inline spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java]: should we keep these comments? Looks like description from the problem statement.

Comment (andrei-ionescu) [reply spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java]: 👍 I will remove the comments.

**Comment by andrei-ionescu** [comment]
@rdblue I implemented the suggestions, please have another look. Thank you.

**Comment by andrei-ionescu** [comment]
@rdblue Please have another look on this. Your suggestions were implemented. Thank you.

**Comment by andrei-ionescu** [comment]
One more ping... @rdblue please have a look on this.

**Comment by rdblue** [comment]
@andrei-ionescu, I'm focused on getting the release out right now. I can take another look after that.

**Comment by rdblue** [comment]
@andrei-ionescu, can you update the PR description with information about how your proposed solution works and what configuration it exposes?

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java [hunk 2]
```diff
@@ -38,7 +38,20 @@
...
+  /**
+   * Returns a list of compatibility errors for writing with the given write schema.
+   *
+   * @param readSchema a read schema
+   * @param writeSchema a write schema
+   * @param disableNullabilityCheck disable the check for nullable on fields
+   * @return a list of error details, or an empty list if there are no compatibility problems
+   */
+  public static List<String> writeCompatibilityErrors(Schema readSchema, Schema writeSchema,
+                                                      Boolean disableNullabilityCheck) {
```
Comment (rdblue) [inline api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: I think this should be `checkNullability`. It's usually easier to understand if boolean are phrased as positive instead of negative: "if not check nullability" vs "if not disable nullability check".

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java [hunk 3]
```diff
@@ -38,7 +38,20 @@
...
+
+  /**
+   * Returns a list of compatibility errors for writing with the given write schema.
+   *
+   * @param readSchema a read schema
+   * @param writeSchema a write schema
+   * @param disableNullabilityCheck disable the check for nullable on fields
+   * @return a list of error details, or an empty list if there are no compatibility problems
+   */
+  public static List<String> writeCompatibilityErrors(Schema readSchema, Schema writeSchema,
```
Comment (rdblue) [inline api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: Is there a better name for this that avoids passing a boolean? Maybe this could be `typeCompatibilityErrors`?

File: core/src/main/java/org/apache/iceberg/TableProperties.java [hunk 4]
```diff
@@ -103,4 +103,7 @@ private TableProperties() {}
 
   public static final String WRITE_TARGET_FILE_SIZE_BYTES = "write.target-file-size-bytes";
   public static final long WRITE_TARGET_FILE_SIZE_BYTES_DEFAULT = Long.MAX_VALUE;
+
+  public static final String DISABLE_NULLABILITY_CHECK = "write.disable-nullability-check";
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/TableProperties.java]: I don't think this should be a table property. It is unlikely that you would want to ignore nullability for all writes to a table. The main problem is cases where a certain path produces a nullable field when the user knows it doesn't contain null, which is a more limited case. I think it makes sense for this to be a write option, and possibly an option that we get from the Spark environment. But I see no reason to make this apply across writes from different engines.

File: spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java [hunk 5]
```diff
@@ -0,0 +1,198 @@
...
+import org.apache.spark.sql.Row;
+import org.apache.spark.sql.SaveMode;
+import org.apache.spark.sql.SparkSession;
+import org.junit.Assert;
+import org.junit.Before;
+import org.junit.Rule;
+import org.junit.Test;
+import org.junit.rules.TemporaryFolder;
+
+public class TestNullableParquet {
```
Comment (rdblue) [inline spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java]: Is there another test that these cases could be added to instead of creating another suite? The Spark session startup takes a while, so we should try to avoid addign new suites. What about `TestDataFrameWrites`?

File: site/docs/configuration.md [hunk 6]
```diff
@@ -94,4 +95,5 @@ df.write
 | ------------ | -------------------------- | ------------------------------------------------------------ |
 | write-format | Table write.format.default | File format to use for this write operation; parquet or avro |
 | target-file-size-bytes | As per table property | Overrides this table's write.target-file-size-bytes     |
+| disable-nullability-check | false         | Disables the nullable check on fields                        |
```
Comment (rdblue) [inline site/docs/configuration.md]: How about `check-nullability` and default it to `true`?

Comment (andrei-ionescu) [reply site/docs/configuration.md]: 👍

File: spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java (hunk 5 above)
Comment (andrei-ionescu) [reply spark/src/test/java/org/apache/iceberg/spark/source/TestNullableParquet.java]: 👍

**Comment by andrei-ionescu** [comment]
@rdblue Addressed the comments... when you have some time please have another look.

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java [hunk 7]
```diff
@@ -38,7 +38,18 @@
    * @return a list of error details, or an empty list if there are no compatibility problems
    */
   public static List<String> writeCompatibilityErrors(Schema readSchema, Schema writeSchema) {
-    return TypeUtil.visit(readSchema, new CheckCompatibility(writeSchema, true));
+    return TypeUtil.visit(readSchema, new CheckCompatibility(writeSchema, true, true));
+  }
+
+  /**
+   * Returns a list of compatibility errors for writing with the given write schema.
```
Comment (rdblue) [inline api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: This doc should be updated to explain how it differs from `writeCompatibilityErrors`. Probably update the doc for that method as well to note that it does check field nullability.

File: spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java [hunk 8]
```diff
@@ -184,4 +219,98 @@ private void writeAndValidateWithLocations(Table table, File location, File expe
     JavaRDD<InternalRow> rdd = sc.parallelize(rows);
     return spark.internalCreateDataFrame(JavaRDD.toRDD(rdd), convert(schema), false);
   }
+
+  @Test
+  public void testNullablePoCWithWriteOption() throws IOException {
```
Comment (rdblue) [inline spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java]: What is "PoC"?

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java (hunk 7 above)
Comment (andrei-ionescu) [reply api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: 👍

File: spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java (hunk 8 above)
Comment (andrei-ionescu) [reply spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java]: I will rename.

**Comment by andrei-ionescu** [comment]
@rdblue I addressed the comments, when you have some time please have another look. Thank you.

**Comment by andrei-ionescu** [comment]
@rdblue Could you have a look into this PR?

**Comment by rdblue** [comment]
Will do. I was out for a couple days, which is why I haven't gotten to it yet.

File: site/docs/configuration.md [hunk 9]
```diff
@@ -43,6 +43,7 @@ Iceberg tables support table properties to configure table behavior, like the de
 | write.metadata.metrics.default     | truncate(16)       | Default metrics mode for all columns in the table; none, counts, truncate(length), or full |
 | write.metadata.metrics.column.col1 | (not set)          | Metrics mode for column 'col1' to allow per-column tuning; none, counts, truncate(length), or full |
 | write.target-file-size-bytes       | Long.MAX_VALUE     | Controls the size of files generated to target about this many bytes. |
+| write.disable-nullability-check    | false              | Disables the nullable check on fields              |
```
Comment (rdblue) [inline site/docs/configuration.md]: I thought this table configuration would be removed? It doesn't make sense to me that you would never want to check nullability for a table. If Spark has a problem, then it should be turned off for individual Spark jobs, or for all Spark jobs in a Spark config.

Comment (rdblue) [reply site/docs/configuration.md]: Also, this is still phrased as a negative, "disable", which we should avoid.

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java [hunk 10]
```diff
@@ -32,13 +32,27 @@
 public class CheckCompatibility extends TypeUtil.CustomOrderSchemaVisitor<List<String>> {
   /**
    * Returns a list of compatibility errors for writing with the given write schema.
+   * This includes the required/optional compatibility of fields and returns error in
+   * case of mismatch.
```
Comment (rdblue) [inline api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: It isn't clear what "required/optional compatibility" is. What about this instead?

> This includes nullability: writing a optional (nullable) values to a required field is an error.

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java (hunk 7 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: Similar to above, I think this wording is difficult to understand. How about this instead?

> `This checks type compatibility and not nullability: writing a optional (nullable) values to a required field is not an error. To check nullability as well as types, use {@link #writeCompatibilityErrors(Schema, Schema)}.`

File: site/docs/configuration.md (hunk 9 above)
Comment (andrei-ionescu) [reply site/docs/configuration.md]: It is removed. I just forgot to modify this section. 👍

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java (hunk 10 above)
Comment (andrei-ionescu) [reply api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: Your wording is better, I modified accordingly. 😄

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java (hunk 7 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: @andrei-ionescu, could you update this one as well?

File: spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java [hunk 11]
```diff
@@ -176,4 +182,13 @@ private void validatePartitionTransforms(PartitionSpec spec) {
           String.format("Cannot write using unsupported transforms: %s", unsupported));
     }
   }
+
+  private boolean checkNullability(DataSourceOptions options) {
+    boolean sparkCheckNullability = Boolean.parseBoolean(lazySpark.conf()
+        .get("spark.sql.iceberg.check-nullability",
+            Boolean.toString(TableProperties.CHECK_NULLABILITY_DEFAULT)));
```
Comment (rdblue) [inline spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java]: Can this be defaulted here to true? This shouldn't be in `TableProperties`.

File: core/src/main/java/org/apache/iceberg/TableProperties.java [hunk 12]
```diff
@@ -103,4 +103,6 @@ private TableProperties() {}
 
   public static final String WRITE_TARGET_FILE_SIZE_BYTES = "write.target-file-size-bytes";
   public static final long WRITE_TARGET_FILE_SIZE_BYTES_DEFAULT = Long.MAX_VALUE;
+
+  public static final boolean CHECK_NULLABILITY_DEFAULT = true;
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/TableProperties.java]: Can you remove this? It isn't a table property so it doesn't make sense to have it here anymore.

Comment (andrei-ionescu) [reply core/src/main/java/org/apache/iceberg/TableProperties.java]: Ok. Will use concrete boolean value.

File: spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java (hunk 11 above)
Comment (andrei-ionescu) [reply spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java]: Ok. Will use concrete boolean value.

**Comment by rdblue** [comment]
One last Javadoc update and I think we can commit this. Thanks, @andrei-ionescu!

File: api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java (hunk 7 above)
Comment (andrei-ionescu) [reply api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java]: 👍

**Comment by andrei-ionescu** [comment]
@rdblue Modified the Javadoc and squashed the commits into one commit.

**Comment by rdblue** [comment]
Merged. Thanks for contributing this fix, @andrei-ionescu!
