### PR TITLE
Fix SchemaVisitor thread safety

### LINKED ISSUE #831: SchemaVisitor should use thread safe structure for fieldIds
When creating Iceberg Schema from Parquet Message in ReadConf.java, it throws exception like below some times. The `fieldIds` access is wrong due to multithread. So we should change to use `ConcurrentLinkedDeque`  instead. It hasn't throw exception after changing to `ConcurrentLinkedDeque`.

```
17:45:13.087 [DEBUG] [TestEventLogger]     [Executor task launch worker for task 57] ERROR org.apache.spark.executor.Executor - Exception in task 0.0 in stage 50.0 (TID 57)
17:45:13.087 [DEBUG] [TestEventLogger]     java.util.NoSuchElementException
17:45:13.087 [DEBUG] [TestEventLogger]          at java.util.LinkedList.removeFirst(LinkedList.java:270)
17:45:13.087 [DEBUG] [TestEventLogger]          at java.util.LinkedList.pop(LinkedList.java:801)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.types.TypeUtil.visit(TypeUtil.java:239)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.types.TypeUtil.visit(TypeUtil.java:225)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.mapping.MappingUtil.create(MappingUtil.java:54)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.parquet.ReadConf.<init>(ReadConf.java:80)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.parquet.ParquetReader.init(ParquetReader.java:64)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.parquet.ParquetReader.iterator(ParquetReader.java:74)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.spark.source.Reader$TaskDataReader.open(Reader.java:563)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.spark.source.Reader$TaskDataReader.open(Reader.java:525)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.spark.source.Reader$TaskDataReader.<init>(Reader.java:444)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.iceberg.spark.source.Reader$ReadTask.createPartitionReader(Reader.java:367)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD.compute(DataSourceRDD.scala:42)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
17:45:13.087 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.scheduler.Task.run(Task.scala:123)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
17:45:13.088 [DEBUG] [TestEventLogger]          at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
17:45:13.088 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:45:13.088 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:45:13.088 [DEBUG] [TestEventLogger]          at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by rdblue**
This fixes #831 by removing the linked list that is accidentally shared between threads when `SchemaVisitor` implementations are singletons. Now, `SchemaVisitor` exposes `beforeField` and `afterField` callbacks so the visitor that uses field IDs can track them itself.

### CODE REVIEW

File: api/src/main/java/org/apache/iceberg/types/TypeUtil.java [hunk 1]
```diff
@@ -190,7 +189,11 @@ public static boolean isPromotionAllowed(Type from, Type.PrimitiveType to) {
   }
 
   public static class SchemaVisitor<T> {
-    private final Deque<Integer> fieldIds = Lists.newLinkedList();
+    public void beforeField(Types.NestedField field) {
```
Comment (openinx) [inline api/src/main/java/org/apache/iceberg/types/TypeUtil.java]: nit: would be better to name the two as preVisitField(...)  & postVisitField(...) ?

Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/types/TypeUtil.java]: Why do you prefer those names? I think they capture the same information.

I'm going to go ahead and merge this since @chenjunjiedada is hitting the problem, but we can rename these later if we think that there is value.
